services:
  postgres_ai_app_data:
    hostname: postgres_ai_app_data
    container_name: postgres0
    image: postgres:16
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data0:/data/db'
    restart: always
  redis_ai_app:
    image: 'redis:7.2.5-alpine'
    container_name: redis_ai_app_data
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data0:/bitnami/redis0/data'

volumes:
  postgres_data0:
    external: true
  redis_data0:
    driver: local